### ISSUE TITLE
Cannot deal with HTML5 element nesting

### ISSUE THREAD

**Issue by demux** [cburgmer/rasterizeHTML.js#32]
The CSS looks like this:

``` css
.c2_col {
    display: block;
    -webkit-column-count: 2;
    -moz-column-count: 2;
    column-count: 2;
}
```
